id: I0D489816
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3877-final
source_file: null
initial_creation_type: input
imported: '2022-08-01T10:24:04.517839'
last_modified: '2022-08-01T10:24:04.517852'
parser: null
source_metadata:
  title: ཐུན་མོང་གི་རྩ་བ།
  base:
    73CB:
      title: ཐུན་མོང་གི་རྩ་བ།
      base_file: 73CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
